"""add_llm_enhancement_fields

Revision ID: 13496df1d35d
Revises: 9e2848f60f63
Create Date: 2026-03-14 23:31:52.717470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13496df1d35d'
down_revision: Union[str, None] = '9e2848f60f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_entity_property', sa.Column('llm_description', sa.Text(), nullable=True, comment='给大模型看的描述(用于精确理解此参数含义)'))
    op.add_column('ai_entity_property', sa.Column('extract_expression', sa.Text(), nullable=True, comment='参数兜底提取规则(正则或表达式)'))
    op.add_column('ai_entity_property', sa.Column('normalization_config', sa.JSON(), nullable=True, comment='归一化配置: 同义词/日期/枚举转换规则(JSON)'))
    op.add_column('ai_entity_property', sa.Column('mapping_config', sa.JSON(), nullable=True, comment='参数映射配置: 转换规则如名称→ID(JSON)'))
    op.alter_column('ai_llm_config', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='提供商: doubao/glm/qwen/minimax/lmstudio/custom',
               existing_comment='提供商: doubao/glm/qwen/custom',
               existing_nullable=False)
    op.add_column('ai_skill', sa.Column('entity_extract_prompt', sa.Text(), nullable=True, comment='实体抽取提示词模板'))
    op.add_column('ai_skill', sa.Column('max_response_tokens', sa.Integer(), nullable=True, comment='最大回复Token(0=使用默认)'))
    op.add_column('ai_skill', sa.Column('max_tool_calls', sa.Integer(), nullable=True, comment='单轮最大工具调用次数'))
    op.add_column('ai_skill', sa.Column('summary_threshold', sa.Integer(), nullable=True, comment='触发历史摘要的轮次阈值'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_skill', 'summary_threshold')
    op.drop_column('ai_skill', 'max_tool_calls')
    op.drop_column('ai_skill', 'max_response_tokens')
    op.drop_column('ai_skill', 'entity_extract_prompt')
    op.alter_column('ai_llm_config', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='提供商: doubao/glm/qwen/custom',
               existing_comment='提供商: doubao/glm/qwen/minimax/lmstudio/custom',
               existing_nullable=False)
    op.drop_column('ai_entity_property', 'mapping_config')
    op.drop_column('ai_entity_property', 'normalization_config')
    op.drop_column('ai_entity_property', 'extract_expression')
    op.drop_column('ai_entity_property', 'llm_description')
    # ### end Alembic commands ###
